services:
  pass-tee-port-enclave:
    image: lorbke/pass-tee-port-enclave
    network_mode: host
    restart: unless-stopped
    volumes:
      - /app:/usr/src/app
    environment:
      - RUST_BACKTRACE=1