services:
  pass-tee-port-enclave:
    image: lorbke/pass-tee-port-enclave
    network_mode: host
    restart: unless-stopped
    volumes:
      - /app/ecdsa.sec:/usr/src/app/ecdsa.sec
    environment:
      - RUST_BACKTRACE=1